### 获取所有服务实例
GET http://localhost:8486/findAll?service=io.github.william.wmrpc.Userservice

### 注册一个实例
POST  http://localhost:8485/reg?service=io.github.william.wmrpc.Userservice
Content-Type: application/json

{
  "context": "wmrpc",
  "host": "localhost",
  "port": "8086",
  "schema": "http",
  "status": false,
  "parameters": {
    "env": "dev",
    "tag": "red"
  }
}

### 取消一个实例
POST  http://localhost:8484/unreg?service=io.github.william.wmrpc.Userservice
Content-Type: application/json

{
  "context": "wmrpc",
  "host": "localhost",
  "port": "8082",
  "schema": "http"
}

### 获取8484服务实例状态
GET http://localhost:8486/health

### 获取8484服务实例版本
GET http://localhost:8484/version?service=io.github.william.wmrpc.Userservice

### 获取8484所有服务实例状态
GET http://localhost:8484/cluster